---
destination : ~/
auto        : false
lsi         : false
rouge       : true
permalink   : none
markdown    : kramdown

#maruku:
kramdown:
    use_divs: true
    use_tex: true
    png_engine : blahtex
    png_dir    : images/latex/
    png_url    : /images/latex/

